server:
  port: 8088
  servlet:
    encoding:
      enable: true
      charset: UTF-8
      force-response: true
spring:
  application:
    name: tvapi
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/tv_db?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: testting7989@gmail.com
    password: khanhduy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    default-property-inclusion: NON_NULL
  security:
    filter:
      order: 10

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      file-size-threshold: 1GB
      location: C:/Users/Admin/Documents/TV
      max-request-size: 1GB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

#properties
file:
  upload-dir: C:/Users/Admin/Documents/TV
